name: Generate snake
on:
schedule:
- cron: "0 */12 * * *"
workflow_dispatch:
permissions:
contents: write
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4
- name: Generate snake SVG
uses: Platane/snk/svg-only@v3
with:
github_user_name: MarcoAmantea
outputs: |
dist/github-contribution-grid-snake.svg
- name: Push snake
run: |
mkdir -p output
mv dist/github-contribution-grid-snake.svg output/
git config user.name "github-actions"
git config user.email "actions@users.noreply.github.com
"
git add -A
git commit -m "chore: update snake" || echo "No changes"
git push
